import { ReactScan } from "@/lib/react-scan";
import { type Metadata } from "next";
import { PropsWithChildren } from "react";
import { Providers } from "@/app/[locale]/providers";
import { type ParamsWithLocale } from "@/types/common";
import { getMessages, setRequestLocale } from "next-intl/server";
import { fonts } from "@/fonts.config";
import "../globals.scss";
import { locales } from "@/i18n/locales";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return locales.map((locale) => ({locale}));
}

export default async function RootLayout({ children, params }: PropsWithChildren<ParamsWithLocale>) {
    const { locale } = await params;

    setRequestLocale(locale);
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <head>
                <ReactScan />
            </head>
            <body className={fonts}>
                <Providers intlConfig={{ messages, locale }}>
                    { children }
                </Providers>
            </body>
        </html>
    );
}
