import { ReactScan } from "@/lib/react-scan";
import { type Metadata, Viewport } from "next";
import { PropsWithChildren } from "react";
import { type ParamsWithLocale } from "@/types/common";
import { getMessages, setRequestLocale } from "next-intl/server";
import { fonts } from "@/fonts.config";
import { NextIntlClientProvider } from "next-intl";
import { ServiceWorkerProvider } from "@/service-worker/client/provider";
import { getSession } from "@/api/auth/get-session";
import { ReactQueryClientProvider } from "@/providers/react-query-provider";
import { StandaloneProvider } from "@/providers/standalone.provider";
import { SessionStoreProvider } from "@/features/session";

import "../globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: [
        { media: "(prefers-color-scheme: dark)", color: "#000000" },
        { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    ],
};

export default async function RootLayout({ children, params }: PropsWithChildren<ParamsWithLocale>) {
    const { locale } = await params;

    setRequestLocale(locale);
    const messages = await getMessages();

    const { data } = await getSession();

    return (
        <html lang={locale}>
            <head>
                <ReactScan />
            </head>
            <body className={fonts}>
                <ServiceWorkerProvider register={process.env.SETVICE_WORKER === "true"}>
                    <NextIntlClientProvider
                        locale={locale}
                        messages={messages}
                    >
                        <ReactQueryClientProvider>
                            <SessionStoreProvider
                                init={[{
                                    user: data,
                                }]}
                            >
                                <StandaloneProvider>
                                    { children }
                                </StandaloneProvider>
                            </SessionStoreProvider>
                        </ReactQueryClientProvider>
                    </NextIntlClientProvider>
                </ServiceWorkerProvider>
            </body>
        </html>
    );
}
