import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import { fonts } from "@/fonts.config";
import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body className={fonts}>
                { children }
            </body>
        </html>
    );
}
